# ______ _            _                                   _
# | ___ \ |          | |                                 | |
# | |_/ / | __ _  ___| | _____ _   _ _ __ _ __ __ _ _ __ | |_
# | ___ \ |/ _` |/ __| |/ / __| | | | '__| '__/ _` | '_ \| __|
# | |_/ / | (_| | (__|   < (__| |_| | |  | | | (_| | | | | |_
# \____/|_|\__,_|\___|_|\_\___|\__,_|_|  |_|  \__,_|_| |_|\__|
# http://patorjk.com/software/taag/#p=testall&f=Blocks&t=Blackcurrant%0A

# Almost all the things in the website can be customized from here.
# Changing title and description according to your website requirement is important.


title: SamSchneider.me
description: I blog about how to build better software by building better teams.
url: https://samschneider.me
# baseurl: /something
# Baseurl is disabled by default. https://ben.balter.com/jekyll-style-guide/config/#baseurl

# buy-link: 
#   rzp: https://rzp.io/l/blackcurrant-theme
#   pp: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=5TM7X9TE7KMKN
# For more customizations, go to  _data/main.yml




# Kramdown is the default markdown processor used. It is supported by Github.
markdown: kramdown

# Mathjax setting
enable-mathjax: yes

# Charts
enable-chartjs: yes


# This defines how the URLs should look like.
permalink: /blog/:title/

# Pagination - Posts per page in the blog index.
paginate: 4
paginate_path: /blog/page:num/


# Jekyll will read contents inside _pages only if we tell it to.
include:
    - _pages

# Google Ananlytics Tracker.
# Sign up with Google analytics and replce with your analytics ID.
analytics: G-4KNQCH6WRH

# Table of contents in each post
# Change the value to 'no' if Table of Contents is not required.
toc:  yes

# Share buttons
# Change it to `no` to remove share buttons.
share: yes


# Comments by Disqus
# Sign up with Disqus to get your shortcode. Leave it blank if you do not want to run diqus code on the website.
# Leave it blank to remove disqus completely.
disqus: webjeda-demo


# Define whether recent posts should be shown at the bottom of each post.
# Change it to `no` to remove recent posts.
recent-posts: yes



# Editing items below this line can break the site
##################################################


#
#   ,-----.                                                    ,--.
#  '  .--./ ,---. ,--,--,--. ,---. ,--.--. ,---.  ,---.  ,---. `--' ,---. ,--,--,
#  |  |    | .-. ||        || .-. ||  .--'| .-. :(  .-' (  .-' ,--.| .-. ||      \
#  '  '--'\' '-' '|  |  |  || '-' '|  |   \   --..-'  `).-'  `)|  |' '-' '|  ||  |
#   `-----' `---' `--`--`--'|  |-' `--'    `----'`----' `----' `--' `---' `--''--'
#                           `--'
# All compression variables are declared here.

sass:
 sass_dir: /assets/css/_sass
 style: compressed

#compress.html
compress_html:
  clippings: [html, head, meta, title, link, body, div, script, header, footer]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


collections:
    books:
        output: true
        permalink: /books/:path/
    chapters:
        output: true
        permalink: /chapters/:path/

exclude:
    - .git
    - vendor
    - node_modules


# These plugins are supported by github by default and can be installed locally using ruby gems
plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-paginate   # Used for sorting posts by page numbers.
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.